#!/bin/sh

# AUTHOR: Warren Crutcher
# use as you wish, but if you improve this, please let me know!
# github.com/warrenlc/diary

usage="USAGE: diary <new> | <entry> | <pdf>"

if [[ $# -ne 1 ]]; then
    echo "Wrong number of arguments."
    echo $usage
    exit
fi

case $1 in 
    
    new)
        exec diary_new
        ;;
    
    entry)
        exec diary_entry
        ;;

    pdf)
        exec diary_pdf
        ;;

    *)
        echo "Invalid arguemnt."
        echo $usage
        ;;
esac

